import argparse
from deriva.core import ErmrestCatalog, get_credential, DerivaPathError
import deriva.core.ermrest_model as em

table_name = 'Biosample'
schema_name = 'Beta_Cell'

column_defs = [
    em.Column.define('Dataset', em.builtin_types['text'],
        nullok=False,
        annotations={'tag:isrd.isi.edu,2017:asset': {}, 'tag:misd.isi.edu,2015:display': {}, 'tag:isrd.isi.edu,2016:column-display': {}},
    ),
    em.Column.define('Summary', em.builtin_types['text'],
    ),
    em.Column.define('Collection_Date', em.builtin_types['date'],
    ),
    em.Column.define('Capillary_Number', em.builtin_types['int2'],
        comment='ID number of the capillary constaining the biosample.',
    ),
    em.Column.define('Sample_Position', em.builtin_types['int2'],
        comment='Position in the capillary where the sample is located.',
    ),
    em.Column.define('Specimen', em.builtin_types['text'],
        annotations={'tag:isrd.isi.edu,2017:asset': {}, 'tag:misd.isi.edu,2015:display': {}, 'tag:isrd.isi.edu,2016:column-display': {}},
        comment='Biological material used for the biosample.',
    ),
    em.Column.define('Specimen_Type', em.builtin_types['text'],
        comment='Method by which specimen is prepared.',
    ),
    em.Column.define('Experiment', em.builtin_types['ermrest_rid'],
        comment='Experiment in which this biosample is used',
    ),
    em.Column.define('Protocol', em.builtin_types['text'],
        comment='Biosample protocol.',
    ),
]


key_defs = [
    em.Key.define(['Dataset', 'Sample_Position', 'Capillary_Number'],
                   constraint_names=[('Beta_Cell', 'Biosample_Capillary_Number_Sample_Position_Key')],
       annotations = {'tag:misd.isi.edu,2015:display': {}},
    ),
    em.Key.define(['Dataset', 'RID'],
                   constraint_names=[('Beta_Cell', 'Biosample_Dataset_RID_Key')],
       annotations = {'tag:misd.isi.edu,2015:display': {}},
    ),
    em.Key.define(['RID'],
                   constraint_names=[('Beta_Cell', 'Biosample_Key')],
       annotations = {'tag:misd.isi.edu,2015:display': {}},
    ),
]


fkey_defs = [
    em.ForeignKey.define(['Dataset', 'Experiment'],
            'isa', 'experiment', ['dataset', 'RID'],
            constraint_names=[('Beta_Cell', 'Biosample_Experiment_Dataset_FKey')],
        acls={'insert': ['*'], 'update': ['*']},
    ),
    em.ForeignKey.define(['Experiment'],
            'isa', 'experiment', ['RID'],
                         annotations={'tag:misd.isi.edu,2015:display': {}, 'tag:isrd.isi.edu,2016:foreign-key': {
                             'domain_filter_pattern': 'dataset={{{_Dataset}}}'}},
            constraint_names=[('Beta_Cell', 'Biosample_Experiment_FKey')],
        acls={'insert': ['*'], 'update': ['*']},
    ),
    em.ForeignKey.define(['Protocol'],
            'Beta_Cell', 'Protocol', ['RID'],
            constraint_names=[('Beta_Cell', 'Biosample_Protocol_FKey')],
        acls={'insert': ['*'], 'update': ['*']},
    ),
    em.ForeignKey.define(['Specimen'],
            'isa', 'specimen', ['RID'],
            constraint_names=[('Beta_Cell', 'Biosample_Specimen_FKey')],
        acls={'insert': ['*'], 'update': ['*']},
    ),
    em.ForeignKey.define(['Dataset'],
            'isa', 'dataset', ['RID'],
                         annotations={'tag:misd.isi.edu,2015:display': {}, 'tag:isrd.isi.edu,2016:foreign-key': {
                             'domain_filter_pattern': 'RID={{{$fkeys.Beta_Cell.Biosample_Experiment_FKey.values._dataset}}}'}},
            constraint_names=[('Beta_Cell', 'Biosample_Dataset_FKey')],
        acls={'insert': ['*'], 'update': ['*']},
        on_update='CASCADE',
        on_delete='RESTRICT',
    ),
    em.ForeignKey.define(['Specimen_Type'],
            'vocab', 'specimen_type_terms', ['id'],
            constraint_names=[('Beta_Cell', 'Biosample_Specimen_Type_FKey')],
        acls={'insert': ['*'], 'update': ['*']},
        comment='Must be a valid reference to a specimen type.',
    ),
]


visible_columns = \
{'*': [['Beta_Cell', 'Biosample_Key'],
       {'markdown_name': 'Dataset',
        'source': [{'outbound': ['Beta_Cell', 'Biosample_Dataset_FKey']},
                   'RID']},
       'Summary',
       {'source': [{'outbound': ['Beta_Cell', 'Biosample_Specimen_FKey']},
                   'RID']},
       {'markdown_name': 'Experiment',
        'source': [{'outbound': ['Beta_Cell', 'Biosample_Experiment_FKey']},
                   'RID']},
       {'source': [{'outbound': ['Beta_Cell', 'Biosample_Experiment_FKey']},
                   'RID']},
       {'markdown_name': 'Cell Line',
        'source': [{'outbound': ['Beta_Cell', 'Biosample_Specimen_FKey']},
                   {'outbound': ['isa', 'specimen_cell_line_fkey']},
                   {'outbound': ['isa', 'cell_line_cell_line_terms_fkey']},
                   'name']},
       {'aggregate': 'array',
        'comment': 'Compound used to treat the cell line for the Experiment',
        'entity': True,
        'markdown_name': 'Additive',
        'source': [{'outbound': ['Beta_Cell', 'Biosample_Specimen_FKey']},
                   {'outbound': ['isa', 'specimen_protocol_fkey']},
                   {'inbound': ['Beta_Cell', 'Protocol_Step_Protocol_FKey']},
                   {'inbound': ['Beta_Cell',
                                'Protocol_Step_Additive_Term_Protocol_Step_FKey']},
                   {'outbound': ['isa',
                                 'protocol_step_additive_term_additive_term_fkey']},
                   'RID']},
       {'aggregate': 'array',
        'comment': 'Concentration of additive applied to cell line in mM',
        'entity': True,
        'markdown_name': 'Concentration',
        'source': [{'outbound': ['Beta_Cell', 'Biosample_Specimen_FKey']},
                   {'outbound': ['isa', 'specimen_protocol_fkey']},
                   {'inbound': ['Beta_Cell', 'Protocol_Step_Protocol_FKey']},
                   {'inbound': ['Beta_Cell',
                                'Protocol_Step_Additive_Term_Protocol_Step_FKey']},
                   'Additive_Concentration']},
       {'aggregate': 'array',
        'comment': 'Duration in minutes of additive applied to cell line in ',
        'entity': True,
        'markdown_name': 'Duration',
        'source': [{'outbound': ['Beta_Cell', 'Biosample_Specimen_FKey']},
                   {'outbound': ['isa', 'specimen_protocol_FKey']},
                   {'inbound': ['Beta_Cell', 'Protocol_Step_Protocol_FKey']},
                   'Duration']},
       ['Beta_Cell', 'Biosample_Specimen_Type_FKey'], 'Capillary_Number',
       'Sample_Position', 'Collection_Date'],
 'entry': [['Beta_Cell', 'Biosample_Dataset_FKey'],
           ['Beta_Cell', 'Biosample_Experiment_FKey'],
           ['Beta_Cell', 'Biosample_Protocol_FKey'],
           ['Beta_Cell', 'Biosample_Specimen_FKey'],
           ['Beta_Cell', 'Biosample_Specimen_Type_FKey'], 'Capillary_Number',
           'Sample_Position', 'collection_date'],
 'filter': {'and': [{'entity': True, 'source': 'RID'},
                    {'source': [{'outbound': ['Beta_Cell',
                                              'Biosample_Dataset_FKey']},
                                'RID']},
                    {'markdown_name': 'Cell Line',
                     'source': [{'outbound': ['Beta_Cell',
                                              'Biosample_Specimen_FKey']},
                                {'outbound': ['isa',
                                              'specimen_cell_line_fkey']},
                                {'outbound': ['isa',
                                              'cell_line_cell_line_terms_fkey']},
                                'name']},
                    {'aggregate': 'array',
                     'comment': 'Additives used to treat the cell line for the '
                                'Experiment',
                     'entity': True,
                     'markdown_name': 'Additive',
                     'source': [{'outbound': ['Beta_Cell',
                                              'Biosample_Specimen_FKey']},
                                {'outbound': ['isa', 'specimen_protocol_fkey']},
                                {'inbound': ['Beta_Cell',
                                             'Protocol_Step_Protocol_FKey']},
                                {'inbound': ['Beta_Cell',
                                             'Protocol_Step_Additive_Term_Protocol_Step_FKey']},
                                {'outbound': ['Beta_Cell',
                                              'Protocol_Step_Additive_Term_Additive_Term_FKey']},
                                'RID']},
                    {'aggregate': 'array',
                     'comment': 'Concentration of additive applied to cell '
                                'line in mM',
                     'entity': True,
                     'markdown_name': 'Concentration',
                     'source': [{'outbound': ['Beta_Cell',
                                              'Biosample_Specimen_FKey']},
                                {'outbound': ['isa', 'specimen_protocol_fkey']},
                                {'inbound': ['Beta_Cell',
                                             'Protocol_Step_Protocol_FKey']},
                                {'inbound': ['Beta_Cell',
                                             'Protocol_Step_Additive_Term_Protocol_Step_FKey']},
                                'Additive_Concentration'],
                     'ux_mode': 'choices'},
                    {'aggregate': 'array',
                     'comment': 'Duration in minutes of additive applied to '
                                'cell line in ',
                     'entity': True,
                     'markdown_name': 'Duration',
                     'source': [{'outbound': ['Beta_Cell',
                                              'Biosample_Specimen_FKey']},
                                {'outbound': ['isa', 'specimen_protocol_FKey']},
                                {'inbound': ['Beta_Cell',
                                             'Protocol_Step_Protocol_FKey']},
                                'Duration'],
                     'ux_mode': 'choices'},
                    ['isa', 'Biosample_Specimen_Type_FKey'],
                    {'source': [{'inbound': ['isa',
                                             'mesh_data_biosample_fkey']},
                                'url']},
                    {'source': [{'inbound': ['isa',
                                             'Processed_Tomography_Data_Biosample_FKey']},
                                'url']},
                    {'entity': True,
                     'source': 'Capillary_Number',
                     'ux_mode': 'choices'}]}}

visible_foreign_keys = \
{'*': [{'source': [{'inbound': ['Beta_Cell',
                                'XRay_Tomography_Data_Biosample_FKey']},
                   'RID']},
       {'source': [{'inbound': ['isa',
                                'Processed_Tomography_Data_Biosample_FKey']},
                   'RID']},
       ['viz', 'model_Biosample_FKey']]}

table_comment = \
None

table_display = \
{'row_name': {'row_markdown_pattern': '{{RID}} - '
                                      '{{summary}}{{#local_identifier}} '
                                      '[{{Capillary_Number}}] '
                                      '{{/local_identifier}}'}}

table_acls = {}
table_acl_bindings = {}
export = \
{'templates': [{'format_name': 'BDBag (Holey)',
                'format_type': 'BAG',
                'name': 'default',
                'outputs': [{'destination': {'name': 'Biosample',
                                             'type': 'csv'},
                             'source': {'api': 'entity',
                                        'table': 'Beta_Cell:Biosample'}},
                            {'destination': {'name': 'MRC', 'type': 'fetch'},
                             'source': {'api': 'attribute',
                                        'path': 'URL,MD5,length:=Byte_Count',
                                        'table': 'Beta_Cell:XRay_Tomography_Data'}},
                            {'destination': {'name': 'processed_data',
                                             'type': 'download'},
                             'source': {'api': 'attribute',
                                        'path': 'url,md5,length:=byte_count',
                                        'table': 'isa:Processed_Tomography_Data'}},
                            {'destination': {'name': 'OBJS', 'type': 'fetch'},
                             'source': {'api': 'attribute',
                                        'path': 'url',
                                        'table': 'isa:mesh_data'}}]},
               {'format_name': 'BDBag',
                'format_type': 'BAG',
                'name': 'default',
                'outputs': [{'destination': {'name': 'Biosample',
                                             'type': 'csv'},
                             'source': {'api': 'entity',
                                        'table': 'Beta_Cell:Biosample'}},
                            {'destination': {'name': 'MRC', 'type': 'download'},
                             'source': {'api': 'attribute',
                                        'path': 'url',
                                        'table': 'Beta_Cell:XRay_Tomography_Data'}},
                            {'destination': {'name': 'processed_data',
                                             'type': 'download'},
                             'source': {'api': 'attribute',
                                        'path': 'url',
                                        'table': 'Beta_Cell:Processed_Tomography_Data'}},
                            {'destination': {'name': 'OBJS',
                                             'type': 'download'},
                             'source': {'api': 'attribute',
                                        'path': 'url',
                                        'table': 'isa:mesh_data'}}]}]}

table_annotations = {
    "tag:isrd.isi.edu,2016:export": export,
    "tag:isrd.isi.edu,2016:table-alternatives":
{}
,
    "tag:isrd.isi.edu,2016:table-display": table_display,
    "tag:misd.isi.edu,2015:display":
{}
,
    "tag:isrd.isi.edu,2016:visible-foreign-keys": visible_foreign_keys,
    "tag:isrd.isi.edu,2016:visible-columns": visible_columns,
}
column_comment = \
{'Capillary_Number': 'ID number of the capillary constaining the biosample.',
 'Experiment': 'Experiment in which this biosample is used',
 'Protocol': 'Biosample protocol.',
 'Sample_Position': 'Position in the capillary where the sample is located.',
 'Specimen': 'Biological material used for the biosample.',
 'Specimen_Type': 'Method by which specimen is prepared.'}

column_annotations = \
{'Dataset': {'tag:isrd.isi.edu,2016:column-display': {},
             'tag:isrd.isi.edu,2017:asset': {},
             'tag:misd.isi.edu,2015:display': {}},
 'Specimen': {'tag:isrd.isi.edu,2016:column-display': {},
              'tag:isrd.isi.edu,2017:asset': {},
              'tag:misd.isi.edu,2015:display': {}}}



table_def = em.Table.define(table_name,
    column_defs=column_defs,
    key_defs=key_defs,
    fkey_defs=fkey_defs,
    annotations=table_annotations,
    acls=table_acls,
    acl_bindings=table_acl_bindings,
    comment=table_comment,
    provide_system = True
)
