import argparse
from deriva.core import ErmrestCatalog, get_credential, DerivaPathError
import deriva.core.ermrest_model as em
    
visible_columns = \
{   '*': ['cell_line', 'capillary_column', 'sample_position'],
    'compact': [   ['isa', 'biosample_pkey'],
                   'local_identifier',
                   {   'markdown_name': 'Cell Line',
                       'source': [   {   'outbound': [   'isa',
                                                         'biosample_specimen_fkey']},
                                     {   'outbound': [   'isa',
                                                         'specimen_cell_line_fkey']},
                                     'name']},
                   {   'markdown_name': 'Gender',
                       'source': [   {   'outbound': [   'isa',
                                                         'biosample_specimen_fkey']},
                                     {   'outbound': [   'isa',
                                                         'specimen_gender_fkey']},
                                     'name']},
                   'species',
                   'capillary_number',
                   'sample_position'],
    'detailed': [   ['isa', 'biosample_pkey'],
                    ['isa', 'biosample_dataset_fkey'],
                    'local_identifier',
                    'summary',
                    ['isa', 'biosample_species_fkey'],
                    ['isa', 'biosample_specimen_fkey'],
                    {   'markdown_name': 'Cell Line',
                        'source': [   {   'outbound': [   'isa',
                                                          'biosample_specimen_fkey']},
                                      {   'outbound': [   'isa',
                                                          'specimen_cell_line_fkey']},
                                      'name']},
                    {   'markdown_name': 'Species',
                        'source': [   {   'outbound': [   'isa',
                                                          'biosample_specimen_fkey']},
                                      {   'outbound': [   'isa',
                                                          'specimen_species_fkey']},
                                      'name']},
                    {   'markdown_name': 'Gender',
                        'source': [   {   'outbound': [   'isa',
                                                          'biosample_specimen_fkey']},
                                      {   'outbound': [   'isa',
                                                          'specimen_gender_fkey']},
                                      'name']},
                    {   'markdown_name': 'Anatomy',
                        'source': [   {   'outbound': [   'isa',
                                                          'biosample_specimen_fkey']},
                                      {   'outbound': [   'isa',
                                                          'specimen_anatomy_fkey']},
                                      'name']},
                    [   ['isa', 'biosample_specimen_fkey'],
                        ['isa', 'specimen_species_fkey']],
                    ['isa', 'biosample_specimen_type_fkey'],
                    'capillary_number',
                    'sample_position',
                    'collection_date'],
    'entry': [   ['isa', 'biosample_dataset_fkey'],
                 'local_identifier',
                 ['isa', 'biosample_specimen_fkey'],
                 ['isa', 'biosample_specimen_type_fkey'],
                 'capillary_number',
                 'sample_position',
                 'collection_date'],
    'filter': {   'and': [   {   'entity': True,
                                 'markdown_name': 'Species',
                                 'open': True,
                                 'source': [   {   'outbound': [   'isa',
                                                                   'biosample_species_fkey']},
                                               'term']},
                             {   'entity': True,
                                 'markdown_name': 'Local Identifier',
                                 'open': False,
                                 'source': 'local_identifier'},
                             {'entity': True, 'source': 'capillary_number'},
                             {   'markdown_name': 'Cell Line',
                                 'source': [   {   'outbound': [   'isa',
                                                                   'biosample_specimen_fkey']},
                                               {   'outbound': [   'isa',
                                                                   'specimen_cell_line_fkey']},
                                               'name']},
                             {   'markdown_name': 'Species',
                                 'source': [   {   'outbound': [   'isa',
                                                                   'biosample_specimen_fkey']},
                                               {   'outbound': [   'isa',
                                                                   'specimen_species_fkey']},
                                               'name']},
                             {   'markdown_name': 'Gender',
                                 'source': [   {   'outbound': [   'isa',
                                                                   'biosample_specimen_fkey']},
                                               {   'outbound': [   'isa',
                                                                   'specimen_gender_fkey']},
                                               'name']},
                             {   'markdown_name': 'Anatomy',
                                 'source': [   {   'outbound': [   'isa',
                                                                   'biosample_specimen_fkey']},
                                               {   'outbound': [   'isa',
                                                                   'specimen_anatomy_fkey']},
                                               'name']}]}}
visible_foreign_keys = \
{   '*': ['cell_line', 'capillary_column', 'sample_position'],
    'compact': [   ['isa', 'biosample_pkey'],
                   'local_identifier',
                   {   'markdown_name': 'Cell Line',
                       'source': [   {   'outbound': [   'isa',
                                                         'biosample_specimen_fkey']},
                                     {   'outbound': [   'isa',
                                                         'specimen_cell_line_fkey']},
                                     'name']},
                   {   'markdown_name': 'Gender',
                       'source': [   {   'outbound': [   'isa',
                                                         'biosample_specimen_fkey']},
                                     {   'outbound': [   'isa',
                                                         'specimen_gender_fkey']},
                                     'name']},
                   'species',
                   'capillary_number',
                   'sample_position'],
    'detailed': [['isa', 'replicate_biosample_fkey']],
    'entry': [['isa', 'replicate_biosample_fkey']],
    'filter': {   'and': [   {   'entity': True,
                                 'markdown_name': 'Species',
                                 'open': True,
                                 'source': [   {   'outbound': [   'isa',
                                                                   'biosample_species_fkey']},
                                               'term']},
                             {   'entity': True,
                                 'markdown_name': 'Local Identifier',
                                 'open': False,
                                 'source': 'local_identifier'},
                             {'entity': True, 'source': 'capillary_number'},
                             {   'markdown_name': 'Cell Line',
                                 'source': [   {   'outbound': [   'isa',
                                                                   'biosample_specimen_fkey']},
                                               {   'outbound': [   'isa',
                                                                   'specimen_cell_line_fkey']},
                                               'name']},
                             {   'markdown_name': 'Species',
                                 'source': [   {   'outbound': [   'isa',
                                                                   'biosample_specime_fkey']},
                                               {   'outbound': [   'isa',
                                                                   'specimen_species_fkey']},
                                               'name']},
                             {   'markdown_name': 'Gender',
                                 'source': [   {   'outbound': [   'isa',
                                                                   'biosample_specimen_fkey']},
                                               {   'outbound': [   'isa',
                                                                   'specimen_gender_fkey']},
                                               'name']},
                             {   'markdown_name': 'Anatomy',
                                 'source': [   {   'outbound': [   'isa',
                                                                   'biosample_specimen_fkey']},
                                               {   'outbound': [   'isa',
                                                                   'specimen_anatomy_fkey']},
                                               'name']}]}}
table_display = \
{   'row_name': {   'row_markdown_pattern': '{{RID}} - '
                                            '{{summary}}{{#local_identifier}} '
                                            '[{{local_identifier}}] '
                                            '{{/local_identifier}}'}}
annotations = \
{   'tag:isrd.isi.edu,2016:table-alternatives': {},
    'tag:isrd.isi.edu,2016:table-display': {   'row_name': {   'row_markdown_pattern': '{{RID}} '
                                                                                       '- '
                                                                                       '{{summary}}{{#local_identifier}} '
                                                                                       '[{{local_identifier}}] '
                                                                                       '{{/local_identifier}}'}},
    'tag:isrd.isi.edu,2016:visible-columns': {   '*': [   'cell_line',
                                                          'capillary_column',
                                                          'sample_position'],
                                                 'compact': [   [   'isa',
                                                                    'biosample_pkey'],
                                                                'local_identifier',
                                                                {   'markdown_name': 'Cell '
                                                                                     'Line',
                                                                    'source': [   {   'outbound': [   'isa',
                                                                                                      'biosample_specimen_fkey']},
                                                                                  {   'outbound': [   'isa',
                                                                                                      'specimen_cell_line_fkey']},
                                                                                  'name']},
                                                                {   'markdown_name': 'Gender',
                                                                    'source': [   {   'outbound': [   'isa',
                                                                                                      'biosample_specimen_fkey']},
                                                                                  {   'outbound': [   'isa',
                                                                                                      'specimen_gender_fkey']},
                                                                                  'name']},
                                                                'species',
                                                                'capillary_number',
                                                                'sample_position'],
                                                 'detailed': [   [   'isa',
                                                                     'biosample_pkey'],
                                                                 [   'isa',
                                                                     'biosample_dataset_fkey'],
                                                                 'local_identifier',
                                                                 'summary',
                                                                 [   'isa',
                                                                     'biosample_species_fkey'],
                                                                 [   'isa',
                                                                     'biosample_specimen_fkey'],
                                                                 {   'markdown_name': 'Cell '
                                                                                      'Line',
                                                                     'source': [   {   'outbound': [   'isa',
                                                                                                       'biosample_specimen_fkey']},
                                                                                   {   'outbound': [   'isa',
                                                                                                       'specimen_cell_line_fkey']},
                                                                                   'name']},
                                                                 {   'markdown_name': 'Species',
                                                                     'source': [   {   'outbound': [   'isa',
                                                                                                       'biosample_specimen_fkey']},
                                                                                   {   'outbound': [   'isa',
                                                                                                       'specimen_species_fkey']},
                                                                                   'name']},
                                                                 {   'markdown_name': 'Gender',
                                                                     'source': [   {   'outbound': [   'isa',
                                                                                                       'biosample_specimen_fkey']},
                                                                                   {   'outbound': [   'isa',
                                                                                                       'specimen_gender_fkey']},
                                                                                   'name']},
                                                                 {   'markdown_name': 'Anatomy',
                                                                     'source': [   {   'outbound': [   'isa',
                                                                                                       'biosample_specimen_fkey']},
                                                                                   {   'outbound': [   'isa',
                                                                                                       'specimen_anatomy_fkey']},
                                                                                   'name']},
                                                                 [   [   'isa',
                                                                         'biosample_specimen_fkey'],
                                                                     [   'isa',
                                                                         'specimen_species_fkey']],
                                                                 [   'isa',
                                                                     'biosample_specimen_type_fkey'],
                                                                 'capillary_number',
                                                                 'sample_position',
                                                                 'collection_date'],
                                                 'entry': [   [   'isa',
                                                                  'biosample_dataset_fkey'],
                                                              'local_identifier',
                                                              [   'isa',
                                                                  'biosample_specimen_fkey'],
                                                              [   'isa',
                                                                  'biosample_specimen_type_fkey'],
                                                              'capillary_number',
                                                              'sample_position',
                                                              'collection_date'],
                                                 'filter': {   'and': [   {   'entity': True,
                                                                              'markdown_name': 'Species',
                                                                              'open': True,
                                                                              'source': [   {   'outbound': [   'isa',
                                                                                                                'biosample_species_fkey']},
                                                                                            'term']},
                                                                          {   'entity': True,
                                                                              'markdown_name': 'Local '
                                                                                               'Identifier',
                                                                              'open': False,
                                                                              'source': 'local_identifier'},
                                                                          {   'entity': True,
                                                                              'source': 'capillary_number'},
                                                                          {   'markdown_name': 'Cell '
                                                                                               'Line',
                                                                              'source': [   {   'outbound': [   'isa',
                                                                                                                'biosample_specimen_fkey']},
                                                                                            {   'outbound': [   'isa',
                                                                                                                'specimen_cell_line_fkey']},
                                                                                            'name']},
                                                                          {   'markdown_name': 'Species',
                                                                              'source': [   {   'outbound': [   'isa',
                                                                                                                'biosample_specimen_fkey']},
                                                                                            {   'outbound': [   'isa',
                                                                                                                'specimen_species_fkey']},
                                                                                            'name']},
                                                                          {   'markdown_name': 'Gender',
                                                                              'source': [   {   'outbound': [   'isa',
                                                                                                                'biosample_specimen_fkey']},
                                                                                            {   'outbound': [   'isa',
                                                                                                                'specimen_gender_fkey']},
                                                                                            'name']},
                                                                          {   'markdown_name': 'Anatomy',
                                                                              'source': [   {   'outbound': [   'isa',
                                                                                                                'biosample_specimen_fkey']},
                                                                                            {   'outbound': [   'isa',
                                                                                                                'specimen_anatomy_fkey']},
                                                                                            'name']}]}},
    'tag:isrd.isi.edu,2016:visible-foreign-keys': {   '*': [   'cell_line',
                                                               'capillary_column',
                                                               'sample_position'],
                                                      'compact': [   [   'isa',
                                                                         'biosample_pkey'],
                                                                     'local_identifier',
                                                                     {   'markdown_name': 'Cell '
                                                                                          'Line',
                                                                         'source': [   {   'outbound': [   'isa',
                                                                                                           'biosample_specimen_fkey']},
                                                                                       {   'outbound': [   'isa',
                                                                                                           'specimen_cell_line_fkey']},
                                                                                       'name']},
                                                                     {   'markdown_name': 'Gender',
                                                                         'source': [   {   'outbound': [   'isa',
                                                                                                           'biosample_specimen_fkey']},
                                                                                       {   'outbound': [   'isa',
                                                                                                           'specimen_gender_fkey']},
                                                                                       'name']},
                                                                     'species',
                                                                     'capillary_number',
                                                                     'sample_position'],
                                                      'detailed': [   [   'isa',
                                                                          'replicate_biosample_fkey']],
                                                      'entry': [   [   'isa',
                                                                       'replicate_biosample_fkey']],
                                                      'filter': {   'and': [   {   'entity': True,
                                                                                   'markdown_name': 'Species',
                                                                                   'open': True,
                                                                                   'source': [   {   'outbound': [   'isa',
                                                                                                                     'biosample_species_fkey']},
                                                                                                 'term']},
                                                                               {   'entity': True,
                                                                                   'markdown_name': 'Local '
                                                                                                    'Identifier',
                                                                                   'open': False,
                                                                                   'source': 'local_identifier'},
                                                                               {   'entity': True,
                                                                                   'source': 'capillary_number'},
                                                                               {   'markdown_name': 'Cell '
                                                                                                    'Line',
                                                                                   'source': [   {   'outbound': [   'isa',
                                                                                                                     'biosample_specimen_fkey']},
                                                                                                 {   'outbound': [   'isa',
                                                                                                                     'specimen_cell_line_fkey']},
                                                                                                 'name']},
                                                                               {   'markdown_name': 'Species',
                                                                                   'source': [   {   'outbound': [   'isa',
                                                                                                                     'biosample_specime_fkey']},
                                                                                                 {   'outbound': [   'isa',
                                                                                                                     'specimen_species_fkey']},
                                                                                                 'name']},
                                                                               {   'markdown_name': 'Gender',
                                                                                   'source': [   {   'outbound': [   'isa',
                                                                                                                     'biosample_specimen_fkey']},
                                                                                                 {   'outbound': [   'isa',
                                                                                                                     'specimen_gender_fkey']},
                                                                                                 'name']},
                                                                               {   'markdown_name': 'Anatomy',
                                                                                   'source': [   {   'outbound': [   'isa',
                                                                                                                     'biosample_specimen_fkey']},
                                                                                                 {   'outbound': [   'isa',
                                                                                                                     'specimen_anatomy_fkey']},
                                                                                                 'name']}]}},
    'tag:misd.isi.edu,2015:display': {}}
table_acls = \
{   'select': [   'https://auth.globus.org/6a96ec62-7032-11e8-9132-0a043b872764',
                  'https://auth.globus.org/176baec4-ed26-11e5-8e88-22000ab4b42b',
                  'https://auth.globus.org/aa5a2f6e-53e8-11e8-b60b-0a7c735d220a',
                  'https://auth.globus.org/9d596ac6-22b9-11e6-b519-22000aef184d']}
column_annotations = \
{   'dataset': {   'tag:isrd.isi.edu,2016:column-display': {},
                   'tag:isrd.isi.edu,2017:asset': {},
                   'tag:misd.isi.edu,2015:display': {}},
    'specimen': {   'tag:isrd.isi.edu,2016:column-display': {},
                    'tag:isrd.isi.edu,2017:asset': {},
                    'tag:misd.isi.edu,2015:display': {}}}

def main():
        parser = argparse.ArgumentParser(description='Load foreign key defs for table isa:biosample')
        parser.add_argument('--server', default='pbcconsortium.isrd.isi.edu',
                            help='Catalog server name')
        args = parser.parse_args()

        server = args.server
        schema_name = 'isa'
        table_name = 'biosample'

        credential = get_credential(server)
        catalog = ErmrestCatalog('https', server, 1, credentials=credential)
        model_root = catalog.getCatalogModel()
        schema = model_root.schemas[schema_name]
        table = schema.tables[table_name]

        if len(visible_columns) > 0:
            for k, v in visible_columns.items():
                table.visible_columns[k] = v

        if len(visible_foreign_keys) > 0:
            for k, v in visible_foreign_keys.items():
                table.visible_foreign_keys[k] = v
        table.annotations['table_display'] = table_display

        table.apply(catalog)


if __name__ == "__main__":
        main()
